name: Run NBA Script with Docker

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Run Docker Image
        run: |
          docker pull as1118/nba_script:latest
          docker run --rm \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            as1118/nba_script:latest
