name: Run NBA Script

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * *"  

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libpq-dev \
            libgmp-dev \
            libudunits2-dev \
            libgeos-dev \
            libproj-dev \
            libgdal-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set GitHub PAT
        run: echo "GITHUB_PAT=${{ secrets.GITHUB_PAT }}" >> $GITHUB_ENV

      - name: Install R packages
        run: |
          Rscript -e 'Sys.setenv(GITHUB_PAT=Sys.getenv("GITHUB_PAT"))'
          Rscript -e 'install.packages(c("tidyverse", "lubridate", "zoo", "DBI", "RPostgres", "future", "jsonlite", "devtools", "remotes"), repos="http://cran.rstudio.com/", dependencies=TRUE)'
          Rscript -e 'remotes::install_github("abresler/nbastatR", dependencies=TRUE)'

      - name: Configure environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Run the NBA script
        run: Rscript nba_script.R
